// Test IDs for StockAuto pages
export const NAV = {
  logo: 'nav-logo',
  home: 'nav-home',
  veiculos: 'nav-veiculos',
  revendedores: 'nav-revendedores',
  planos: 'nav-planos',
  login: 'nav-login',
  cadastro: 'nav-cadastro',
  painel: 'nav-painel',
  admin: 'nav-admin',
  logout: 'nav-logout',
  userMenu: 'nav-user-menu',
};

export const HOMEPAGE = {
  hero: 'home-hero',
  heroCta: 'home-hero-cta',
  heroCtaPainel: 'home-hero-cta-painel',
  searchInput: 'home-search-input',
  searchSubmit: 'home-search-submit',
  categoryCard: (slug) => `home-category-${slug}`,
  featuredGrid: 'home-featured-grid',
  dealersSection: 'home-dealers-section',
  vehicleCard: (id) => `home-vehicle-card-${id}`,
};

export const LISTING = {
  page: 'listing-page',
  filterCategory: 'listing-filter-category',
  filterBrand: 'listing-filter-brand',
  filterUf: 'listing-filter-uf',
  filterCity: 'listing-filter-city',
  filterPriceMin: 'listing-filter-price-min',
  filterPriceMax: 'listing-filter-price-max',
  filterYearMin: 'listing-filter-year-min',
  filterYearMax: 'listing-filter-year-max',
  filterQ: 'listing-filter-q',
  filterApply: 'listing-filter-apply',
  filterReset: 'listing-filter-reset',
  results: 'listing-results',
  vehicleCard: (id) => `listing-vehicle-card-${id}`,
};

export const DETAIL = {
  page: 'detail-page',
  title: 'detail-title',
  price: 'detail-price',
  gallery: 'detail-gallery',
  specs: 'detail-specs',
  description: 'detail-description',
  whatsappCta: 'detail-whatsapp-cta',
  whatsappStickyMobile: 'detail-whatsapp-sticky-mobile',
  callDealer: 'detail-call-dealer',
  shareWhatsapp: 'detail-share-whatsapp',
  shareCopy: 'detail-share-copy',
  dealerCard: 'detail-dealer-card',
  dealerLink: 'detail-dealer-link',
};

export const DEALER = {
  page: 'dealer-page',
  cover: 'dealer-cover',
  logo: 'dealer-logo',
  name: 'dealer-name',
  whatsapp: 'dealer-whatsapp-cta',
  inventoryGrid: 'dealer-inventory',
  vehicleCard: (id) => `dealer-vehicle-card-${id}`,
};

export const AUTH = {
  loginEmail: 'login-email',
  loginPassword: 'login-password',
  loginSubmit: 'login-submit',
  loginError: 'login-error',
  registerEmail: 'register-email',
  registerPassword: 'register-password',
  registerStore: 'register-store',
  registerPhone: 'register-phone',
  registerWhatsapp: 'register-whatsapp',
  registerCity: 'register-city',
  registerUf: 'register-uf',
  registerPlanAvulso: 'register-plan-avulso',
  registerPlanLoja: 'register-plan-loja',
  registerSubmit: 'register-submit',
  registerError: 'register-error',
  pixScreen: 'register-pix-screen',
  pixKey: 'register-pix-key',
  pixCopy: 'register-pix-copy',
  pixGoPainel: 'register-pix-go-painel',
};

export const DPANEL = {
  page: 'dpanel-page',
  tabVehicles: 'dpanel-tab-vehicles',
  tabProfile: 'dpanel-tab-profile',
  tabPlan: 'dpanel-tab-plan',
  newVehicle: 'dpanel-new-vehicle',
  vehicleRow: (id) => `dpanel-vehicle-row-${id}`,
  vehicleEdit: (id) => `dpanel-vehicle-edit-${id}`,
  vehicleDelete: (id) => `dpanel-vehicle-delete-${id}`,
  vehicleFormCategory: 'dpanel-vform-category',
  vehicleFormBrand: 'dpanel-vform-brand',
  vehicleFormModel: 'dpanel-vform-model',
  vehicleFormVersion: 'dpanel-vform-version',
  vehicleFormYearMade: 'dpanel-vform-year-made',
  vehicleFormYearModel: 'dpanel-vform-year-model',
  vehicleFormKm: 'dpanel-vform-km',
  vehicleFormTransmission: 'dpanel-vform-transmission',
  vehicleFormFuel: 'dpanel-vform-fuel',
  vehicleFormColor: 'dpanel-vform-color',
  vehicleFormCity: 'dpanel-vform-city',
  vehicleFormUf: 'dpanel-vform-uf',
  vehicleFormPrice: 'dpanel-vform-price',
  vehicleFormDescription: 'dpanel-vform-description',
  vehicleFormPhotos: 'dpanel-vform-photos',
  vehicleFormSubmit: 'dpanel-vform-submit',
  vehicleFormCancel: 'dpanel-vform-cancel',
  profileSubmit: 'dpanel-profile-submit',
  profileLogoUpload: 'dpanel-profile-logo-upload',
  profileCoverUpload: 'dpanel-profile-cover-upload',
};

export const APANEL = {
  page: 'apanel-page',
  tabDealers: 'apanel-tab-dealers',
  tabVehicles: 'apanel-tab-vehicles',
  tabNotifications: 'apanel-tab-notifications',
  tabSettings: 'apanel-tab-settings',
  dealerRow: (id) => `apanel-dealer-row-${id}`,
  dealerApprove: (id) => `apanel-dealer-approve-${id}`,
  dealerBlock: (id) => `apanel-dealer-block-${id}`,
  dealerDelete: (id) => `apanel-dealer-delete-${id}`,
  vehicleRow: (id) => `apanel-vehicle-row-${id}`,
  vehicleApprove: (id) => `apanel-vehicle-approve-${id}`,
  vehicleReject: (id) => `apanel-vehicle-reject-${id}`,
  notifRow: (id) => `apanel-notif-row-${id}`,
  settingsPix: 'apanel-settings-pix',
  settingsPixHolder: 'apanel-settings-pix-holder',
  settingsSubmit: 'apanel-settings-submit',
};
